CUT-2378: -Attribues Object needs custom type
TheJumpCloud/jcapi-powershell pull request #69
Opened 2024-02-07 21:02 UTC by gweinjc

## Issues
* [CUT-2378](https://jumpcloud.atlassian.net/browse/CUT-2378) - -Attribues Object needs custom type

## What does this solve?
Through some discovery it was determined that the -Attributes object is being flattened by the SDKs and does not necessarily need a custom type. 

As an example the following script would set sudo to enabled and withoutPassword to false
```powershell
$attributes = [JumpCloud.SDK.V2.Models.IGraphOperationSystemAttributes]@{ 'sudo' = @{'enabled' = $true; 'withoutPassword' = $false } }
Set-JcSdkSystemAssociation -SystemId 61982961719e942987898f39 -id 5ef5fe69a899bd46963ab24a -op 'update' -type 'user' -Attributes $attributes
```

We can achieve the same result by doing the following:
```powershell
Set-JcSdkSystemAssociation -SystemId 61982961719e942987898f39 -id 5ef5fe69a899bd46963ab24a -op 'update' -type 'user' -Attributes @{ 'sudoEnabled' = $true; 'SudoWithoutPassword' = $true }
```

This is due to the SDKs doing a sort of flattening to the sudo object and allowing us to instead call the sudoEnabled or SudoWithoutPassword property to set those values.

Rather than creating a custom object, we can update the documentation for this functionality

This behavior can also be applied to the `Set-JcSdkUserAssociation` function

## Is there anything particularly tricky?
N/A

## How should this be tested?

Pull the branch and import the updated version of the V2 SDK
Attempt to run the following script and ensure that the results are updated in the console:
```powershell
Set-JcSdkSystemAssociation -SystemId <SystemID> -id <UserID> -op 'update' -type 'user' -Attributes @{ 'sudoEnabled' = $true; 'SudoWithoutPassword' = $true }
```

2024-02-07 22:44 UTC, jworkmanjc requested changes
I think everything looks fine to me, Just two suggestions on the examples, if you remove associations from on object you technically don't need to pass in an attributes object. I think we should mark our examples this way but open for debate

2024-02-07 22:44 UTC, jworkmanjc commented on SDKs/PowerShell/JumpCloud.SDK.V2/custom/generated/Set-JcSdkSystemAssociation.ps1
> +PS C:\> Set-JcSdkSystemAssociation -SystemId <SystemID> -id <UserID> -op 'remove' -type 'user' -Attributes @{ 'sudoEnabled' = $false; 'SudoWithoutPassword' = $false }
One thing some customers might like better is just. It does the same thing, that's the whole bit we added to the build custom functions

`Set-JcSdkSystemAssociation -SystemId <SystemID> -id <UserID> -op 'remove' -type 'user'`

2024-02-07 22:44 UTC, jworkmanjc commented on SDKs/PowerShell/JumpCloud.SDK.V2/custom/generated/Set-JcSdkSystemAssociation.ps1
> +.Example
same thing here, there's no need to pass in attributes when you remove a system association we can just do:

`Set-JcSdkSystemAssociation -SystemId <SystemID> -id <UserGroupID> -op 'remove' -type 'user_group'`

2024-02-07 22:44 UTC, jworkmanjc commented on SDKs/PowerShell/JumpCloud.SDK.V2/custom/generated/Set-JcSdkUserAssociation.ps1
> +PS C:\> Set-JcSdkUserAssociation -UserId <UserID> -id <SystemID> -op 'remove' -type 'user' -Attributes @{ 'sudoEnabled' = $false; 'SudoWithoutPassword' = $false }
```suggestion
PS C:\> Set-JcSdkUserAssociation -UserId <UserID> -id <SystemID> -op 'remove' -type 'user'
```

2024-02-07 22:44 UTC, jworkmanjc commented on SDKs/PowerShell/JumpCloud.SDK.V2/custom/generated/Set-JcSdkUserAssociation.ps1
> +PS C:\> Set-JcSdkUserAssociation -UserId <UserID> -id <SystemGroupID> -op 'remove' -type 'system_group' -Attributes @{ 'sudoEnabled' = $false; 'SudoWithoutPassword' = $false }
```suggestion
PS C:\> Set-JcSdkUserAssociation -UserId <UserID> -id <SystemGroupID> -op 'remove' -type 'system_group'
```

2024-02-08 17:15 UTC, jworkmanjc approved these changes
Thanks for the examples!

2024-02-08 18:54 UTC, kmaranionjc approved these changes
Tests worked and code looks good. Great work

2024-02-08 22:25 UTC, merged